spring:
  cache:
    redis:
      time-to-live: 600000
      expiration: 600
  redis:
    database: 0
    host: 192.168.80.132
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 200
        min-idle: 2
    password: 123456
    port: 6379
    timeout: 6000
    #sentinel:
      #master: mymaster
      #nodes: 10.150.146.14:17002,10.150.146.15:17001,10.150.146.16:17000
  datasource:
    druid:
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;druid.stat.logSlowSql=true
      keep-alive: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      # 初始化大小
      initial-size: 2
      # 最大连接数
      max-active: 10
      max-pool-prepared-statement-per-connection-size: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 最小连接数
      min-idle: 1
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 30000
      url: jdbc:mysql://192.168.80.132:3306/hyassistant?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      username: root
      password: 123456
      validation-query: SELECT 1 FROM DUAL
      # StatViewServlet配置
      stat-view-servlet:
        allow:
        deny:
        enabled: true
        login-username:
        login-password:
        reset-enable: false
        url-pattern: /druid/*
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        principal-cookie-name:
        principal-session-name:
        profile-enable:
        session-stat-enable:
        session-stat-max-count:
        url-pattern: /*
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: mix-music
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:**/mapper/xml/*.xml
  type-aliases-package: com.happycoding.music.entity
logging:
  level:
    root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS}[${spring.application.name}][%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId}][%-5level][%logger{36}]:%msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS}[${spring.application.name}][%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId}][%-5level][%logger{36}]:%msg%n'
  file:
    name: './logs/${spring.application.name}_${server.port}.log'
server:
  port: 8100
#spring 异步执行线程
async:
  pool:
    # 核心线程池大小
    core-pool-size: 2
    # 最大线程数
    max-pool-size: 5
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 20
#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: ""
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间
  token-validity: 43200
  # token 续期检查时间范围（默认30分钟，单位秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800
  # 续期时间范围，默认1小时，单位秒
  renew: 3600
#系统设置
system:
  #单一登录
  single-login: true
  #开启验证码
  enable-captcha: false